ActivityAssets = {

    INTRO = "intro_cutscene",
    DEATH = "death",

    HEART_RED = "heart",
    HEART_RED_HALF = "heart_half",
    HEART_SOUL = "soul_heart",
    HEART_SOUL_HALF = "soul_heart_half",
    HEART_BLACK = "black_heart",
    HEART_BLACK_HALF = "black_heart_half",

    TITLE_1 = "title_1",
    TITLE_2 = "title_2",
    TITLE_3 = "title_3",
    TITLE_4 = "title_4",
    TITLE_5 = "title_5",
    TITLE_6 = "title_6",
    TITLE_7 = "title_7",

    DIFFICULTY_NORMAL = "normal",
    DIFFICULTY_HARD = "hard",
    DIFFICULTY_GREED = "greed",
    DIFFICULTY_GREEDIER = "greedier",

    PLAYER_UNKNOWN = "unknown",

    PLAYER_ISAAC = "playerportrait_isaac",
    PLAYER_MAGDALENE = "playerportrait_magdalene",
    PLAYER_CAIN = "playerportrait_cain",
    PLAYER_JUDAS = "playerportrait_judas",
    PLAYER_DARK_JUDAS = "playerportrait_darkjudas",
    PLAYER_BLUE_BABY = "playerportrait_bluebaby",
    PLAYER_EVE = "playerportrait_eve",
    PLAYER_SAMSON = "playerportrait_samson",
    PLAYER_AZAZEL = "playerportrait_azazel",
    PLAYER_LAZARUS = "playerportrait_lazarus",
    PLAYER_LAZARUS_RISEN = "playerportrait_lazarus2",
    PLAYER_EDEN = "playerportrait_eden",
    PLAYER_LOST = "playerportrait_thelost",
    PLAYER_LILITH = "playerportrait_lilith",
    PLAYER_KEEPER = "playerportrait_keeper",
    PLAYER_APOLLYON = "playerportrait_apollyon",
    PLAYER_FORGOTTEN = "playerportrait_theforgotten",
    PLAYER_BETHANY = "playerportrait_bethany",
    PLAYER_JACOB_ESAU = "playerportrait_jacob",

    PLAYER_ISAAC_TAINTED = "playerportrait_isaac_b",
    PLAYER_MAGDALENE_TAINTED = "playerportrait_magdalene_b",
    PLAYER_CAIN_TAINTED = "playerportrait_cain_b",
    PLAYER_JUDAS_TAINTED = "playerportrait_judas_b",
    PLAYER_BLUE_BABY_TAINTED = "playerportrait_bluebaby_b",
    PLAYER_EVE_TAINTED = "playerportrait_eve_b",
    PLAYER_SAMSON_TAINTED = "playerportrait_samson_b",
    PLAYER_AZAZEL_TAINTED = "playerportrait_azazel_b",
    PLAYER_LAZARUS_TAINTED = "playerportrait_lazarus_b",
    PLAYER_LAZARUS_DEAD_TAINTED = "playerportrait_lazarus_b_dead",
    PLAYER_EDEN_TAINTED = "playerportrait_eden_b",
    PLAYER_LOST_TAINTED = "playerportrait_thelost_b",
    PLAYER_LILITH_TAINTED = "playerportrait_lilith_b",
    PLAYER_KEEPER_TAINTED = "playerportrait_keeper_b",
    PLAYER_APOLLYON_TAINTED = "playerportrait_apollyon_b",
    PLAYER_FORGOTTEN_TAINTED = "playerportrait_theforgotten_b",
    PLAYER_BETHANY_TAINTED = "playerportrait_bethany",
    PLAYER_JACOB_ESAU_TAINTED = "playerportrait_jacob_b",

    PLAYER_JACOB = "playerportrait_jacob_b",
    PLAYER_DARK_ESAU = "playerportrait_jacob_b_darkesau",
    PLAYER_THELOST = "playerportrait_thelost",
    PLAYER_THELOST_TAINTED = "playerportrait_thelost_b",
    PLAYER_THEFORGOTTEN = "playerportrait_theforgotten",
    PLAYER_THEFORGOTTEN_TAINTED = "playerportrait_theforgotten_b",
    PLAYER_LAZARUS_DEAD = "playerportrait_lazarus_b_dead",

    PLAYER_FIEND = "playerportrait_fiend",
    PLAYER_FIEND_TAINTED = "playerportrait_fiend_b",
    PLAYER_GOLEM = "playerportrait_golem",
    PLAYER_ANDROMEDA = "playerportrait_andromeda",
    PLAYER_ANDROMEDA_TAINTED = "playerportrait_andromeda_b",
    PLAYER_BAEL = "playerportrait_bael",
    PLAYER_BERTRAN = "playerportrait_bertran",
    PLAYER_ARACHNA = "playerportrait_arachna",
    PLAYER_ARACHNA_TAINTED = "playerportrait_arachna",
    PLAYER_CAR = "playerportrait_car",
    PLAYER_DANTE = "playerportrait_dante",
    PLAYER_DELETED = "playerportrait_deleted",
    PLAYER_DELETED_TAINTED = "playerportrait_deleted_b",
    PLAYER_EEVEE = "playerportrait_eevee",
    PLAYER_TARNISHED_ISAAC = "playerportrait_epiphany_isaac",
    PLAYER_TARNISHED_MAGDALENE = "playerportrait_epiphany_magdalene",
    PLAYER_TARNISHED_CAIN = "playerportrait_epiphany_cain",
    PLAYER_TARNISHED_JUDAS = "playerportrait_epiphany_judas",
    PLAYER_TARNISHED_SAMSON = "playerportrait_epiphany_samson",
    PLAYER_TARNISHED_EDEN = "playerportrait_epiphany_eden",
    PLAYER_TARNISHED_LOST = "playerportrait_epiphany_lost",
    PLAYER_TARNISHED_KEEPER = "playerportrait_epiphany_keeper",
    PLAYER_ICARUS = "playerportrait_icarus",
    PLAYER_MAMMON = "playerportrait_mammon",
    PLAYER_MAMMON_TAINTED = "playerportrait_mammon_b",
    PLAYER_SAMAEL = "playerportrait_samael",
    PLAYER_SAMAEL_TAINTED = "playerportrait_samael_b",
    PLAYER_SARAH = "playerportrait_sarah",
    PLAYER_SHERIFF = "playerportrait_sheriff",
    PLAYER_SODOM_GOMORRAH = "playerportrait_sodomgomorrah",
    PLAYER_SODOM_GOMORRAH_TAINTED = "playerportrait_sodomgomorrah_b",
    PLAYER_DREAM_GUARD = "playerportrait_thedreamguard",

}